sudo: false
language: go
env:
  - DEP_VERSION="0.5.0"
go:
    - "1.11"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12
install:
  - dep ensure
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
before_script:
  - make golangci-lint
script:
  - make test
after_success:
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
